site_name: Mkdocs Material Social Card Testing
site_description: 'Resources learning social Open Graph metadata.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/mkdocs-material-social'
repo_url: 'https://github.com/dmccreary/mkdocs-material-social'

nav:
  - Home: index.md
  - Simulations:
    - Introduction: sims/index.md
    - Bouncing Ball: sims/bouncing-ball/index.md
    - Gold Star: sims/gold-star/index.md
    - Polygon: sims/polygon/index.md
    - Sphere: sims/sphere/index.md
    - Override Test: sims/override-test/index.md
  - References: references.md
  - Contact: contact.md

# Dan's MicroSite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  # logo: img/logo.png
  # favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
  # this is the new line but make sure to follow the brew installs
  - social
markdown_extensions:
   - attr_list
   - md_in_html
   - admonition
   - pymdownx.details
   - pymdownx.superfences
   - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-BBR7MPK96Z