site_name: Mkdocs Material Social Card Testing
site_description: 'Resources learning social Open Graph metadata.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/mkdocs-material-social'
repo_url: 'https://github.com/dmccreary/mkdocs-material-social'

nav:
  - Home: index.md
  - Social Override Plugin: social-override.md
  - Gallery: gallery.md
  - Micro Simulations:
    - Introduction: sims/index.md
    - Bouncing Ball: sims/bouncing-ball/index.md
    - Gold Star: sims/gold-star/index.md
    - Polygon: sims/polygon/index.md
    - Sphere: sims/sphere/index.md
    - Override Test: sims/override-test/index.md
    - Template: sims/template/index.md
  - Grid Test: grid-test.md
  - Metadata Override Test: metadata-override-test.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md
  - Test Metadata: test-metadata.md

# Dan's MicroSite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/local-image.png
  custom_dir: overrides
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
plugins:
  - search
  - social
  - social_override
extra_css:
  - css/extra.css
markdown_extensions:
   - attr_list
   - md_in_html
   - admonition
   - pymdownx.details
   - pymdownx.superfences
   - pymdownx.highlight:
      linenums: true